name: mohrazium
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

#!#########################
dependencies:
  animations: ^2.0.3
  blurrycontainer: ^1.0.2
  bot_toast: ^4.0.2
  built_collection: ^5.1.1
  built_value: ^8.3.3
  carousel_slider: ^4.1.1
  eva_icons_flutter: ^3.1.0
  fast_i18n: ^5.12.6
  floy:
    path: /home/mohrazium/Projects/Flutter/Plugins/Floy-Workspace/floy/
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.6+1
  flutter_modular: ^5.0.3
  flutter_multi_formatter: ^2.5.1
  intl: ^0.17.0
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  loading_animation_widget: ^1.1.0+5
  logging: ^1.0.1
  mobx: ^2.0.7+5
  percent_indicator: ^4.0.0
  persian_datetime_picker: ^2.5.0
  persian_tools: ^1.0.1
  shamsi_date: ^1.0.1

#!#########################
dev_dependencies:
  build: ^2.3.0
  build_runner: ^2.1.11
  built_value_generator: ^8.3.3
  dependency_validator: ^3.0.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.7
#!#########################
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Sahel
      fonts:
        - asset: assets/fonts/sahel/sahel.ttf
        - asset: assets/fonts/sahel/sahel_bold.ttf
        - asset: assets/fonts/sahel/sahel_black.ttf
        - asset: assets/fonts/sahel/sahel_light.ttf
        - asset: assets/fonts/sahel/sahel_semi_bold.ttf